version: '3.1'

services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_api
      MYSQL_USER: root
    ports:
      - "3306:3306"